# AUTO-GENERATED by `generate-eom` -- DO NOT EDIT
# Re-generate with: pixi run generate-eom
# Sympy expression hash: a92c9326f5a229b6

import numpy as np

SYMPY_HASH = "a92c9326f5a229b6"


def compute_M(u_s, v_s, xd_s, yd_s, ud_s, vd_s, m_b, m_d, m_hat_d, m_tilde_d, m_tilde_b, l, g, k_b, k_d, U_b, V_b, U_d, V_d):
    """Compute the 4x4 mass matrix (vectorized over numpy arrays).

    Returns:
        Tuple of (M_00, M_01, M_02, M_03, M_11, M_12, M_13,
        M_22, M_23, M_33) -- upper-triangle elements.
    """
    x0 = m_d + m_tilde_d
    x1 = m_b + m_tilde_b + x0
    x2 = u_s**2
    x3 = v_s**2
    x4 = x3 + 4
    x5 = -x2 + x4
    x6 = x2 + x4
    x7 = l*x0/x6**2
    x8 = 4*x7
    x9 = u_s*v_s
    x10 = -8*x7*x9
    x11 = x2 - x3 + 4
    x12 = 4*x2*x3
    x13 = x12 + x5**2
    x14 = l**2/x6**4
    x15 = 16*x14
    x16 = x11**2 + x12
    M_00 = x1
    M_01 = 0
    M_02 = x5*x8
    M_03 = x10
    M_11 = x1
    M_12 = x10
    M_13 = x11*x8
    M_22 = x15*(m_d*(x13 + 16*x2) + m_tilde_d*x13)
    M_23 = -256*m_tilde_d*x14*x9
    M_33 = x15*(m_d*(x16 + 16*x3) + m_tilde_d*x16)
    return M_00, M_01, M_02, M_03, M_11, M_12, M_13, M_22, M_23, M_33


def compute_F(u_s, v_s, xd_s, yd_s, ud_s, vd_s, m_b, m_d, m_hat_d, m_tilde_d, m_tilde_b, l, g, k_b, k_d, U_b, V_b, U_d, V_d):
    """Compute the 4-component force vector (vectorized over numpy arrays).

    Returns:
        Tuple of (F_0, F_1, F_2, F_3).
    """
    x0 = u_s**2
    x1 = v_s**2
    x2 = x0 + x1
    x3 = x2 + 4
    x4 = x3**3
    x5 = x4**(-1.0)
    x6 = u_s*ud_s
    x7 = v_s*vd_s
    x8 = x6 + x7
    x9 = 4*x8**2
    x10 = ud_s**2 + vd_s**2
    x11 = 2*x8
    x12 = u_s*x9 - x3*(u_s*x10 + ud_s*x11)
    x13 = 8*l
    x14 = x13*(m_d + m_tilde_d)
    x15 = -xd_s
    x16 = U_b + x15
    x17 = x3**2
    x18 = -yd_s
    x19 = V_b + x18
    x20 = k_b*x17*np.sqrt(x16**2 + x19**2)
    x21 = x13*x8
    x22 = u_s*x21
    x23 = 4*l
    x24 = x23*x3
    x25 = ud_s*x24
    x26 = x17*(U_d + x15) + x22 - x25
    x27 = v_s*x21
    x28 = vd_s*x24
    x29 = x17*(V_d + x18) + x27 - x28
    x30 = k_d*np.sqrt(x26**2 + x29**2)
    x31 = x30/x17
    x32 = v_s*x9 - x3*(v_s*x10 + vd_s*x11)
    x33 = g*(m_d - m_hat_d)
    x34 = x3**4*x33
    x35 = x2 - 4
    x36 = x33*x35*x4
    x37 = 4*x8
    x38 = u_s*x37
    x39 = v_s*x38
    x40 = u_s*vd_s + ud_s*v_s
    x41 = x3*x40
    x42 = x39 - x41
    x43 = x17*yd_s - x27 + x28
    x44 = x17*xd_s - x22 + x25
    x45 = x44*(x0*x37 - x3*(3*x6 + x7))
    x46 = x42*x43 + x45
    x47 = 4*m_tilde_d
    x48 = u_s*v_s
    x49 = 2*x48
    x50 = -x0 + x1 + 4
    x51 = 2*x30/x3
    x52 = l*x37
    x53 = x52*(ud_s*x17 - x3*(ud_s*x35 + x38) + x35*x38)
    x54 = 4*m_d
    x55 = -8*l*u_s*v_s*x32 + x12*x23*x50 - x3*x40*x43 + x39*x43 + x45
    x56 = x23*(x10*x17 - x3*(x10*x35 + x9) + x35*x9)
    x57 = 2*l/x3**5
    x58 = x43*(x1*x37 - x3*(x6 + 3*x7))
    x59 = x42*x44 + x58
    x60 = x0 - x1 + 4
    x61 = v_s*x37
    x62 = x52*(vd_s*x17 - x3*(vd_s*x35 + x61) + x35*x61)
    x63 = -x12*x13*x48 + x23*x32*x60 + x39*x44 - x41*x44 + x58
    F_0 = -x5*(x12*x14 - x3*(x16*x20 + x26*x31))
    F_1 = -x5*(x14*x32 - x3*(x19*x20 + x29*x31))
    F_2 = x57*(-u_s*x34 + u_s*x36 + x46*x47 - x47*x55 - x51*(-x26*x50 + x29*x49) + x54*(x46 + x53) + x54*(-u_s*x56 - x53 - x55))
    F_3 = -x57*(v_s*x34 - v_s*x36 - x47*x59 + x47*x63 + x51*(x26*x49 - x29*x60) - x54*(x59 + x62) + x54*(v_s*x56 + x62 + x63))
    return F_0, F_1, F_2, F_3
