"""CLI for drogued_drifters code generation and cache management.

Usage::

    pixi run generate-eom          # generate _generated_eom.py (deprecated)
    pixi run generate-eom --check  # verify freshness (deprecated)
    pixi run save-eom-cache        # save symbolic EOM to .srepr cache file
"""

import hashlib
from pathlib import Path

import click
import sympy as sp
from sympy.printing.numpy import NumPyPrinter

from drogued_drifters.lagrange_model import _derive_symbolic

OUTPUT_PATH = Path(__file__).resolve().parent / "_generated_eom.py"

HEADER_TEMPLATE = """\
# AUTO-GENERATED by `generate-eom` -- DO NOT EDIT
# Re-generate with: pixi run generate-eom
# Sympy expression hash: {sym_hash}

import numpy as np

SYMPY_HASH = "{sym_hash}"
"""


def _arg_names(args):
    """Return the Python identifier for each symbol in args."""
    return [str(s) for s in args]


def _render_cse(replacements, printer):
    """Render CSE intermediate assignments as Python lines."""
    lines = []
    for sym, expr in replacements:
        lines.append(f"    {sym} = {printer.doprint(expr)}")
    return lines


def _symbolic_hash(M_sub, F_sub):
    """Compute a hash of the symbolic M and F expressions."""
    content = str(M_sub) + str(F_sub)
    return hashlib.sha256(content.encode()).hexdigest()[:16]


def generate_source():
    """Run the derivation, apply CSE, and return the generated source code."""
    click.echo("Running sympy derivation (this may take a minute)...")
    M_sub, F_sub, args = _derive_symbolic()

    # Verify M is symmetric
    assert (M_sub - M_sub.T).simplify() == sp.zeros(4, 4), "M is not symmetric!"

    sym_hash = _symbolic_hash(M_sub, F_sub)
    arg_names = _arg_names(args)
    printer = NumPyPrinter()

    # -- compute_M --
    m_exprs = []
    m_labels = []
    for i in range(4):
        for j in range(i, 4):
            m_exprs.append(M_sub[i, j])
            m_labels.append((i, j))

    replacements_m, reduced_m = sp.cse(m_exprs, optimizations="basic")

    lines_m = []
    lines_m.append(f"def compute_M({', '.join(arg_names)}):")
    lines_m.append('    """Compute the 4x4 mass matrix (vectorized over numpy arrays).')
    lines_m.append("")
    lines_m.append("    Returns:")
    lines_m.append("        Tuple of (M_00, M_01, M_02, M_03, M_11, M_12, M_13,")
    lines_m.append("        M_22, M_23, M_33) -- upper-triangle elements.")
    lines_m.append('    """')
    lines_m.extend(_render_cse(replacements_m, printer))
    for expr, (i, j) in zip(reduced_m, m_labels):
        lines_m.append(f"    M_{i}{j} = {printer.doprint(expr)}")
    ret_names = ", ".join(f"M_{i}{j}" for i, j in m_labels)
    lines_m.append(f"    return {ret_names}")

    # -- compute_F --
    f_exprs = [F_sub[i] for i in range(4)]
    replacements_f, reduced_f = sp.cse(f_exprs, optimizations="basic")

    lines_f = []
    lines_f.append(f"def compute_F({', '.join(arg_names)}):")
    lines_f.append('    """Compute the 4-component force vector (vectorized over numpy arrays).')
    lines_f.append("")
    lines_f.append("    Returns:")
    lines_f.append("        Tuple of (F_0, F_1, F_2, F_3).")
    lines_f.append('    """')
    lines_f.extend(_render_cse(replacements_f, printer))
    for idx, expr in enumerate(reduced_f):
        lines_f.append(f"    F_{idx} = {printer.doprint(expr)}")
    lines_f.append("    return F_0, F_1, F_2, F_3")

    header = HEADER_TEMPLATE.format(sym_hash=sym_hash)
    source = header + "\n\n" + "\n".join(lines_m) + "\n\n\n" + "\n".join(lines_f) + "\n"
    source = source.replace("numpy.", "np.")
    return source


@click.command()
@click.option(
    "--check",
    is_flag=True,
    help="Compare generated output to existing file; exit nonzero if different.",
)
def generate_eom(check):
    """Generate (or verify) _generated_eom.py from the sympy derivation."""
    source = generate_source()

    if check:
        if not OUTPUT_PATH.exists():
            click.echo(f"FAIL: {OUTPUT_PATH} does not exist.", err=True)
            raise SystemExit(1)
        existing = OUTPUT_PATH.read_text()
        if existing == source:
            click.echo("OK: generated code is up to date.")
            raise SystemExit(0)
        else:
            click.echo(
                f"FAIL: {OUTPUT_PATH} is out of date. "
                "Re-run: pixi run generate-eom",
                err=True,
            )
            raise SystemExit(1)

    OUTPUT_PATH.write_text(source)
    click.echo(f"Wrote {OUTPUT_PATH}")


@click.command()
def save_eom_cache():
    """Save the symbolic EOM to .srepr cache file.

    This pre-computes the symbolic derivation once and writes it to
    src/drogued_drifters/data/symbolic_eom.srepr for faster imports.
    """
    cache_path = Path(__file__).resolve().parent / "data" / "symbolic_eom.srepr"
    cache_path.parent.mkdir(parents=True, exist_ok=True)

    click.echo("Running sympy derivation (this may take a minute)...")
    M_sub, F_sub, args = _derive_symbolic()

    arg_names = ','.join(str(s) for s in args)
    content = f"{sp.srepr(M_sub)}\n---\n{sp.srepr(F_sub)}\n---\n{arg_names}\n"

    cache_path.write_text(content)
    click.echo(f"Wrote {cache_path}")
